###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: shortskiller
    type: browser-extension
    version: {{package.version}}
    description: {{package.description}}
    logo: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/banner.png"


###############################################################################
