###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: shortskiller
    name: Shorts Killer
    type: browser-extension
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: https://chrome.google.com/webstore/detail/stylegpt/khoggafmiibmeihpkpbkllkkdfhmokoj
    repo: https://github.com/pigeonposse/shortskiller
    logo: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/banner.png"


###############################################################################
