###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: shortskiller
    name: Shorts Killer
    type: 
      - browser-extension
      - chrome-extension
      - firefox-extension
      - edge-extension
      - safari-extension
      - chromium-extension
      - brave-extension
      - opera-extension
      - operagx-extension
      - yandex-extension
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    repo: https://github.com/pigeonposse/shortskiller
    logo: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/shortskiller/main/docs/banner.png"


###############################################################################
